/** @type {import('next').NextConfig} */
const { i18n } = require('./next-i18next.config')
const withPWA = require('next-pwa')({
  dest: 'public'
})


const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ['drupal.ampere.corrupted.pw'],
  },
  i18n,

  async redirects() {
    return [
      // English redirects
      {
        source: '/accessibility/why-accessibility',
        destination: '/accessibility-fundamentals/the-basics/why-focus-on-accessibility',
        locale: false,
        permanent: true,
      },
      {
        source: '/accessibility/accessibility-policy',
        destination: '/accessibility-fundamentals/documents/accessibility-policy',
        locale: false,
        permanent: true,
      },
      {
        source: '/accessibility/accessibility-statement',
        destination: '/accessibility-fundamentals/documents/accessibility-statement',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/great-resources-learn-about-accessibility',
        destination: '/accessibility-fundamentals/places-to-learn-about-accessibility/web-resources-on-accessibility',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/courses-accessibility',
        destination: '/accessibility-fundamentals/places-to-learn-about-accessibility/courses-on-accessibility',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/articles-and-books-accessibility',
        destination: '/accessibility-fundamentals/places-to-learn-about-accessibility/articles-and-books-on-accessibility',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/accessibility-social-media',
        destination: '/accessibility-fundamentals/places-to-learn-about-accessibility/follow-accessibility-content-in-social-media',
        locale: false,
        permanent: true,
      },
      {
        source: '/accessibility/accessibility-auditing',
        destination: '/testing-for-accessibility/accessibility-audit/how-to-do-accessibility-auditing',
        locale: false,
        permanent: true,
      },
      {
        source: '/accessibility/fixing-audit-report-findings',
        destination: '/testing-for-accessibility/accessibility-audit/fixing-audit-report-findings',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/testing-accessibility',
        destination: '/',
        locale: false,
        permanent: true,
      },
      {
        source: '/testing-for-accessibility/accessibility-audit/tools-and-techniques-for-accessibility-testing',
        destination: '/',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/using-voiceover',
        destination: '/testing-for-accessibility/using-assistive-technologies/using-voiceover',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/using-nvda',
        destination: '/testing-for-accessibility/using-assistive-technologies/using-nvda',
        locale: false,
        permanent: true,
      },
      {
        source: '/wcag/what-wcag',
        destination: '/ensuring-accessibility-compliance/wcag/what-is-wcag',
        locale: false,
        permanent: true,
      },
      {
        source: '/wcag/general-information-wcag-terminology',
        destination: '/ensuring-accessibility-compliance/wcag/wcag-terminology',
        locale: false,
        permanent: true,
      },
      {
        source: '/wcag/wcag-tips-perceivable',
        destination: '/ensuring-accessibility-compliance/wcag/wcag-tips-perceivable',
        locale: false,
        permanent: true,
      },
      {
        source: '/wcag/wcag-tips-operable',
        destination: '/ensuring-accessibility-compliance/wcag/wcag-tips-operable',
        locale: false,
        permanent: true,
      },
      {
        source: '/wcag/wcag-tips-understandable',
        destination: '/ensuring-accessibility-compliance/wcag/wcag-tips-understandable',
        locale: false,
        permanent: true,
      },
      {
        source: '/wcag/wcag-tips-robust',
        destination: '/ensuring-accessibility-compliance/wcag/wcag-tips-robust',
        locale: false,
        permanent: true,
      },
      {
        source: '/atag/what-atag',
        destination: '/ensuring-accessibility-compliance/atag/what-is-atag',
        locale: false,
        permanent: true,
      },
      {
        source: '/atag/atag-terminology',
        destination: '/ensuring-accessibility-compliance/atag/atag-terminology',
        locale: false,
        permanent: true,
      },
      {
        source: '/atag/atag-structure',
        destination: '/ensuring-accessibility-compliance/atag/atag-structure',
        locale: false,
        permanent: true,
      },
      {
        source: '/atag/checking-atag-conformance',
        destination: '/ensuring-accessibility-compliance/atag/checking-for-atag-conformance',
        locale: false,
        permanent: true,
      },
      {
        source: '/wai-aria/what-wai-aria',
        destination: '/ensuring-accessibility-compliance/wai-aria/what-is-wai-aria',
        locale: false,
        permanent: true,
      },
      {
        source: '/wai-aria/aria-roles',
        destination: '/ensuring-accessibility-compliance/wai-aria/aria-roles',
        locale: false,
        permanent: true,
      },
      {
        source: '/wai-aria/aria-properties',
        destination: '/ensuring-accessibility-compliance/wai-aria/aria-properties',
        locale: false,
        permanent: true,
      },
      {
        source: '/wai-aria/aria-live-regions',
        destination: '/ensuring-accessibility-compliance/wai-aria/aria-live-regions',
        locale: false,
        permanent: true,
      },
      {
        source: '/wai-aria/aria-states',
        destination: '/ensuring-accessibility-compliance/wai-aria/aria-states',
        locale: false,
        permanent: true,
      },
      {
        source: '/designers/structure-and-functionality',
        destination: '/ensuring-accessibility-compliance/for-designers/structure-and-functionality',
        locale: false,
        permanent: true,
      },
      {
        source: '/designers/fonts',
        destination: '/ensuring-accessibility-compliance/for-designers/fonts',
        locale: false,
        permanent: true,
      },
      {
        source: '/designers/color-contrast-and-other-visual-cues',
        destination: '/ensuring-accessibility-compliance/for-designers/color-contrast-and-other-visual-cues',
        locale: false,
        permanent: true,
      },
      {
        source: '/designers/design-tips-text-content',
        destination: '/ensuring-accessibility-compliance/for-designers/design-tips-for-text-content',
        locale: false,
        permanent: true,
      },
      {
        source: '/designers/designing-forms',
        destination: '/ensuring-accessibility-compliance/for-designers/designing-forms',
        locale: false,
        permanent: true,
      },
      {
        source: '/designers/designing-animations-and-moving-content',
        destination: '/ensuring-accessibility-compliance/for-designers/designing-animations-and-moving-content',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/helpful-resources-designers',
        destination: '/ensuring-accessibility-compliance/for-designers/helpful-resources-for-designers',
        locale: false,
        permanent: true,
      },
      {
        source: '/developers/page-structure-and-functionality',
        destination: '/ensuring-accessibility-compliance/for-developers/page-structure-and-functionality',
        locale: false,
        permanent: true,
      },
      {
        source: '/developers/language',
        destination: '/ensuring-accessibility-compliance/for-developers/language',
        locale: false,
        permanent: true,
      },
      {
        source: '/developers/forms',
        destination: '/ensuring-accessibility-compliance/for-developers/forms',
        locale: false,
        permanent: true,
      },
      {
        source: '/developers/iframes',
        destination: '/ensuring-accessibility-compliance/for-developers/iframes',
        locale: false,
        permanent: true,
      },
      {
        source: '/developers/developing-keyboard-and-screen-reader-users',
        destination: '/ensuring-accessibility-compliance/for-developers/developing-for-keyboard-and-screen-reader-users',
        locale: false,
        permanent: true,
      },
      {
        source: '/developers/website-styles',
        destination: '/ensuring-accessibility-compliance/for-developers/website-styles',
        locale: false,
        permanent: true,
      },
      {
        source: '/resources/helpful-resources-developers',
        destination: '/ensuring-accessibility-compliance/for-developers/helpful-resources-for-developers',
        locale: false,
        permanent: true,
      },
      {
        source: '/writers/writing-website-text-content',
        destination: '/ensuring-accessibility-compliance/for-content-creators/writing-website-text-content',
        locale: false,
        permanent: true,
      },
      {
        source: '/writers/creating-non-text-content',
        destination: '/ensuring-accessibility-compliance/for-content-creators/creating-non-text-content',
        locale: false,
        permanent: true,
      },
      {
        source: '/writers/creating-documents',
        destination: '/ensuring-accessibility-compliance/for-content-creators/creating-documents',
        locale: false,
        permanent: true,
      },
      {
        source: '/writers/social-media',
        destination: '/ensuring-accessibility-compliance/for-content-creators/social-media-and-accessibility',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/111-non-text-content-alt-attribute',
        destination: '/demo/perceivable/1-1-1-non-text-content-alt-attribute',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/131-tables',
        destination: '/demo/perceivable/1-3-1-tables',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/143-contrast',
        destination: '/demo/perceivable/1-4-3-contrast',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/211-keyboard',
        destination: '/demo/operable/2-1-1-keyboard',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/247-focus-visible',
        destination: '/demo/operable/2-4-7-focus-visible',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/253-label-name',
        destination: '/demo/operable/2-5-3-label-in-name',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/312-language-parts',
        destination: '/demo/understandable/3-1-2-language-of-parts',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/412-name-role-value',
        destination: '/demo/robust/4-1-2-name-role-value',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/form-field-instructions',
        destination: '/demo/other/form-field-instructions',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/hashtags-and-screen-readers',
        destination: '/demo/other/hashtags-and-screen-readers',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/pseudo-elements-and-after',
        destination: '/demo/other/pseudo-elements-before-and-after',
        locale: false,
        permanent: true,
      },
      {
        source: '/demos/removing-list-style-list-element',
        destination: '/demo/other/removing-list-style-from-a-list-element',
        locale: false,
        permanent: true,
      },
      // Finnish redirects
      {
        source: '/fi/saavutettavuus/miksi-panostaa-saavutettavuuteen',
        destination: '/fi/saavutettavuuden-perusteet/perusjutut/miksi-panostaa-saavutettavuuteen',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/saavutettavuus/saavutettavuuskaytannot',
        destination: '/fi/saavutettavuuden-perusteet/dokumentaatio/saavutettavuuskaytannot',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/saavutettavuus/saavutettavuusseloste',
        destination: '/fi/saavutettavuuden-perusteet/dokumentaatio/saavutettavuusseloste',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/hyvia-saavutettavuusresursseja',
        destination: '/fi/saavutettavuuden-perusteet/missa-oppia-saavutettavuudesta/saavutettavuusmateriaalia-netissa',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/saavutettavuuskursseja',
        destination: '/fi/saavutettavuuden-perusteet/missa-oppia-saavutettavuudesta/kursseja-saavutettavuudesta',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/artikkeleita-ja-kirjoja-saavutettavuudesta',
        destination: '/fi/saavutettavuuden-perusteet/missa-oppia-saavutettavuudesta/artikkeleita-ja-kirjoja-saavutettavuudesta',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/saavutettavuudesta-sosiaalisessa-mediassa',
        destination: '/fi/saavutettavuuden-perusteet/missa-oppia-saavutettavuudesta/saavutettavuudesta-sosiaalisessa-mediassa',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/saavutettavuus/saavutettavuuden-auditointi',
        destination: '/fi/saavutettavuuden-testaaminen/saavutettavuusauditointi/miten-tehda-saavutettavuusauditointi',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/saavutettavuus/auditointiraportissa-listattujen-ongelmien-korjaus',
        destination: '/fi/saavutettavuuden-testaaminen/saavutettavuusauditointi/auditointiraportissa-listattujen-ongelmien-korjaus',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/saavutettavuuden-testaus',
        destination: '/fi/saavutettavuuden-testaaminen/saavutettavuusauditointi/tyokaluja-ja-tekniikoita-saavutettavuuden-testaamiseen',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/voiceoverin-kaytto',
        destination: '/fi/saavutettavuuden-testaaminen/avustavien-teknologioiden-kayttaminen/voiceoverin-kayttaminen',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/nvdan-kaytto',
        destination: '/fi/saavutettavuuden-testaus/avustavien-teknologioiden-kayttaminen/nvdan-kayttaminen',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wcag/mika-wcag',
        destination: '/fi/saavutettavuuden-varmistaminen/wcag/mika-on-wcag',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wcag/yleista-tietoa-wcagn-termistosta',
        destination: '/fi/saavutettavuuden-varmistaminen/wcag/yleista-tietoa-wcagn-termistosta',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wcag/wcag-vinkkeja-havaittava',
        destination: '/fi/saavutettavuuden-varmistaminen/wcag/wcag-vinkkeja-havaittava',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wcag/wcag-vinkkeja-hallittava',
        destination: '/fi/saavutettavuuden-varmistaminen/wcag/wcag-vinkkeja-hallittava',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wcag/wcag-vinkkeja-ymmarrettava',
        destination: '/fi/saavutettavuuden-varmistaminen/wcag/wcag-vinkkeja-ymmarrettava',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wcag/wcag-vinkkeja-toimintavarma',
        destination: '/fi/saavutettavuuden-varmistaminen/wcag/wcag-vinkkeja-toimintavarma',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/atag/mika-atag',
        destination: '/fi/saavutettavuuden-varmistaminen/atag/mika-on-atag',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/atag/atag-termistoa',
        destination: '/fi/saavutettavuuden-varmistaminen/atag/atag-termistoa',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/atag/atagin-rakenne',
        destination: '/fi/saavutettavuuden-varmistaminen/atag/atagin-rakenne',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/atag/miten-tarkistaa-atagin-vaatimustenmukaisuus',
        destination: '/fi/saavutettavuuden-varmistaminen/atag/miten-tarkistaa-atagin-vaatimustenmukaisuus',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wai-aria/mika-wai-aria',
        destination: '/fi/saavutettavuuden-varmistaminen/wai-aria/mika-on-wai-aria',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wai-aria/aria-roolit',
        destination: '/fi/saavutettavuuden-varmistaminen/wai-aria/aria-roolit',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wai-aria/aria-ominaisuudet',
        destination: '/fi/saavutettavuuden-varmistaminen/wai-aria/aria-ominaisuudet',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wai-aria/aria-live-alueet',
        destination: '/fi/saavutettavuuden-varmistaminen/wai-aria/aria-live-alueet',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/wai-aria/aria-tilat',
        destination: '/fi/saavutettavuuden-varmistaminen/wai-aria/aria-tilat',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/suunnittelijoille/rakenne-ja-toiminnallisuudet',
        destination: '/fi/saavutettavuuden-varmistaminen/suunnittelijoille/rakenne-ja-toiminnallisuudet',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/suunnittelijoille/fontit',
        destination: '/fi/saavutettavuuden-varmistaminen/suunnittelijoille/fontit',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/suunnittelijoille/vari-kontrasti-ja-muut-visuaaliset-vihjeet',
        destination: '/fi/saavutettavuuden-varmistaminen/suunnittelijoille/vari-kontrasti-ja-muut-visuaaliset-vihjeet',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/suunnittelijoille/vinkkeja-tekstisisallon-suunnitteluun',
        destination: '/fi/saavutettavuuden-varmistaminen/suunnittelijoille/vinkkeja-tekstisisallon-suunnitteluun',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/suunnittelijoille/lomakkeiden-suunnittelu',
        destination: '/fi/saavutettavuuden-varmistaminen/suunnittelijoille/lomakkeiden-suunnittelu',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/suunnittelijoille/animaatioiden-ja-liikkuvan-sisallon-suunnittelu',
        destination: '/fi/saavutettavuuden-varmistaminen/suunnittelijoille/animaatioiden-ja-liikkuvan-sisaelloen-suunnittelu',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/materiaalia-ja-tyokaluja-suunnittelijoille',
        destination: '/fi/saavutettavuuden-varmistaminen/suunnittelijoille/materiaalia-ja-tyokaluja-suunnittelijoille',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/kehittajille/rakenne-ja-toiminnallisuus',
        destination: '/fi/saavutettavuuden-varmistaminen/kehittajille/rakenne-ja-toiminnallisuus',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/kehittajille/kieli',
        destination: '/fi/saavutettavuuden-varmistaminen/kehittajille/kieli',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/kehittajille/lomakkeet',
        destination: '/fi/saavutettavuuden-varmistaminen/kehittajille/lomakkeet',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/kehittajille/iframet',
        destination: '/fi/saavutettavuuden-varmistaminen/kehittajille/iframet',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/kehittajille/nappaimistoa-ja-ruudunlukijaa-kayttavien-huomioiminen',
        destination: '/fi/saavutettavuuden-varmistaminen/kehittajille/nappaimistoa-ja-ruudunlukijaa-kayttavien-huomioiminen',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/kehittajille/sivuston-tyylit',
        destination: '/fi/saavutettavuuden-varmistaminen/kehittajille/sivuston-tyylit',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/materiaalia/hyodyllista-materiaalia-kehittajille',
        destination: '/fi/saavutettavuuden-varmistaminen/kehittajille/hyodyllista-materiaalia-kehittajille',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/sisallontuottajille/saavutettavan-tekstisisallon-kirjoittaminen',
        destination: '/fi/saavutettavuuden-varmistaminen/sisallontuottajille/saavutettavan-tekstisisallon-kirjoittaminen',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/sisallontuottajille/ei-tekstuaalisen-sisallon-tuottaminen',
        destination: '/fi/saavutettavuuden-varmistaminen/sisallontuottajille/ei-tekstuaalisen-sisaellon-tuottaminen',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/sisallontuottajille/saavutettavat-tiedostot',
        destination: '/fi/saavutettavuuden-varmistaminen/sisallontuottajille/saavutettavat-tiedostot',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/sisallontuottajille/sosiaalinen-media',
        destination: '/fi/saavutettavuuden-varmistaminen/sisallontuottajille/sosiaalinen-media-ja-saavutettavuus',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/111-ei-tekstuaalinen-sisalto-alt-attribuutti',
        destination: '/fi/demo/havaittava/1-1-1-ei-tekstuaalinen-sisalto-alt-attribuutti',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/131-taulukot',
        destination: '/fi/demo/havaittava/1-3-1-taulukot',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/143-kontrasti',
        destination: '/fi/demo/havaittava/1-4-3-kontrasti',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/211-nappaimisto',
        destination: '/fi/demo/hallittava/2-1-1-nappaimisto',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/247-nakyva-kohdistus',
        destination: '/fi/demo/hallittava/2-4-7-nakyva-kohdistus',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/253-nimilappu-nimessa',
        destination: '/fi/demo/hallittava/2-5-3-nimilappu-nimessa',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/312-osien-kieli',
        destination: '/fi/demo/ymmarrettava/3-1-2-osien-kieli',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/412-nimi-rooli-arvo',
        destination: '/fi/demo/toimintavarma/4-1-2-nimi-rooli-arvo',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/lomakkeen-kenttien-ohjeistukset',
        destination: '/fi/demo/muut/lomakkeen-kenttien-ohjeistukset',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/hashtagit-ja-ruudunlukijat',
        destination: '/fi/demo/muut/hashtagit-ja-ruudunlukijat',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/pseudo-elemetit-ja-after',
        destination: '/fi/demo/muut/pseudo-elemetit-before-ja-after',
        locale: false,
        permanent: true,
      },
      {
        source: '/fi/demot/listatyylin-poistaminen-listaelementilta',
        destination: '/fi/demo/muut/listatyylin-poistaminen-listaelementilta',
        locale: false,
        permanent: true,
      }
    ]
  },
}

module.exports = withPWA(nextConfig)
